substitutions:
  devicename: xy6015lv-2
  friendly_name: xy6015lv-2
  device_description: XY6015LV блок питания N2
  tx_pin: "GPIO5"
  rx_pin: "GPIO4"

esp8266:
  board: d1_mini

logger:
  baud_rate: 0
  level: DEBUG
  hardware_uart: UART1

# Enable Home Assistant API
api:
  encryption:
    key: "JNTJpW/xwbi/lrHF6E7SYJu3NTaf5Ej3QF5c19QwhYo="

ota:
  - platform: esphome
    password: "44caf2d5e2abd75134040fd5b8dd9748"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xy6015Lv-2 Fallback Hotspot"
    password: "IQbfqhtDm6hq"


esphome:
  name: $devicename
  comment: ${device_description}
  friendly_name: $friendly_name

captive_portal:

web_server:
  port: 80  
  version: 3
  log: False

uart:
  id: uart_0
  baud_rate: 115200
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

modbus:
  id: modbus0
  uart_id: uart_0
  send_wait_time: 50ms

modbus_controller:
  - id: xy_hub
    address: 1
    modbus_id: modbus0
    command_throttle: 200ms
    update_interval: 2s

sensor:
  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: input_voltage
    name: "${devicename} Input Voltage"
    register_type: holding
    address: 5
    value_type: U_WORD
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    register_count: 1

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: output_voltage
    name: "${devicename} Output Voltage"
    register_type: holding
    address: 2
    value_type: U_WORD
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    register_count: 1

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: input_current
    name: "${devicename} Output Ah"
    register_type: holding
    address: 6
    value_type: U_WORD
    unit_of_measurement: "Ah"
    accuracy_decimals: 2
    filters:
      - multiply: 0.001
    register_count: 1

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: output_current
    name: "${devicename} Output Current"
    register_type: holding
    address: 3
    value_type: U_WORD
    unit_of_measurement: "A"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    register_count: 1

  

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: output_power
    name: "${devicename} Output Power"
    register_type: holding
    address: 4
    value_type: U_WORD
    unit_of_measurement: "W"
    accuracy_decimals: 4
    filters:
      - multiply: 0.1
    register_count: 1

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: temperature
    name: "${devicename} Temperature"
    register_type: holding
    address: 13
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    register_count: 1
    filters:
      - multiply: 0.1

  # Счетчики энергии (READ-ONLY, адреса 8-11) - 32-bit
  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: output_ah_low
    name: "${devicename} Output Ah (Low)"
    register_type: holding
    address: 8  # AH-LOW (Read-only)
    value_type: U_WORD
    unit_of_measurement: "mAh"
    accuracy_decimals: 0
    internal: true
    register_count: 1

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: output_ah_high
    name: "${devicename} Output Ah (High)"
    register_type: holding
    address: 9  # AH-HIGH (Read-only)
    value_type: U_WORD
    unit_of_measurement: "mAh"
    accuracy_decimals: 0
    internal: true
    register_count: 1

  - platform: template
    name: "${devicename} Output Wh"
    unit_of_measurement: "Wh"
    accuracy_decimals: 3
    lambda: |-
      uint32_t value = ((uint32_t)id(output_ah_high).state * 65536) + (uint32_t)id(output_ah_low).state;
      return value / 1000.0;
    update_interval: 5s

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: output_time_low
    name: "${devicename} Output time (H)"
    register_type: holding
    address: 10  # Output time hours (Read-only)
    value_type: U_WORD
    unit_of_measurement: "h"
    accuracy_decimals: 0
    internal: true
    register_count: 1

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: output_time_high
    name: "${devicename} Output time (min)"
    register_type: holding
    address: 11  # Out time minutes (Read-only)
    value_type: U_WORD
    unit_of_measurement: "min"
    accuracy_decimals: 0
    internal: true
    register_count: 1

  - platform: template
    name: "${devicename} Output time"
    unit_of_measurement: "min"
    #accuracy_decimals: 0
    lambda: |-
      return id(output_time_low).state*60 + id(output_time_high).state;
    
    update_interval: 5s
 
  # Чтение установленных защит S-OAH (регистры 88-89) - 32-bit
  # LCD работает в диапазоне 0-99.99 Ah (делитель 100)
  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: read_oah_low
    name: "${devicename} S-OAH Low"
    register_type: holding
    address: 88  # S-OAH_L
    value_type: U_WORD
    internal: true
    register_count: 1

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: read_oah_high
    name: "${devicename} S-OAH High"
    register_type: holding
    address: 89  # S-OAH_H
    value_type: U_WORD
    internal: true
    register_count: 1

  - platform: template
    id: current_oah_setting
    name: "${devicename} Current Max Charge Setting"
    unit_of_measurement: "Ah"
    accuracy_decimals: 2
    lambda: |-
      uint32_t value = ((uint32_t)id(read_oah_high).state * 65536) + (uint32_t)id(read_oah_low).state;
      return value / 100.0;  // Äåëèòåëü 100 äëÿ äèàïàçîíà 0-99.99
    update_interval: 5s
    on_value:
      then:
        - lambda: |-
            // Îáíîâëÿåì number òîëüêî åñëè çíà÷åíèå èçìåíèëîñü
            if (id(set_oah).state != x) {
              auto call = id(set_oah).make_call();
              call.set_value(x);
              call.perform();
            }

  # Чтение установленных защит S-OWH (регистры 90-91) - 32-bit
  # LCD работает в диапазоне 0-99.99 Wh (делитель 100)
  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: read_owh_low
    name: "${devicename} S-OWH Low"
    register_type: holding
    address: 90  # S-OWH_L
    value_type: U_WORD
    internal: true
    register_count: 1

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: read_owh_high
    name: "${devicename} S-OWH High"
    register_type: holding
    address: 91  # S-OWH_H
    value_type: U_WORD
    internal: true
    register_count: 1

  - platform: template
    id: current_owh_setting
    name: "${devicename} Current Max Energy Setting"
    unit_of_measurement: "Wh"
    accuracy_decimals: 1
    lambda: |-
      uint32_t value = ((uint32_t)id(read_owh_high).state * 65536) + (uint32_t)id(read_owh_low).state;
      return value / 10.0;
    update_interval: 5s
    on_value:
      then:
        - lambda: |-
            // Обновляем number только если значение изменилось
            if (id(set_owh).state != x) {
              auto call = id(set_owh).make_call();
              call.set_value(x);
              call.perform();
            }

  

  - platform: wifi_signal
    name: ${friendly_name}_wifi_signal
    update_interval: 60s
    id: wifi_signal_id

number:
  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: set_output_voltage
    name: "${devicename} Set Output Voltage"
    min_value: 0
    max_value: 60
    step: 0.01
    unit_of_measurement: "V"
    address: 0
    value_type: U_WORD
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: set_output_current
    name: "${devicename} Set Output Current"
    min_value: 0
    max_value: 16
    step: 0.01
    unit_of_measurement: "A"
    address: 1
    value_type: U_WORD
    multiply: 100


  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: set_output_ovp
    name: "${devicename} Set Output OVP (Max Voltage)"
    min_value: 0
    max_value: 65
    step: 0.01
    unit_of_measurement: "V"
    icon: "mdi:arrow-collapse-up"
    address: 83
    value_type: U_WORD
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: set_output_ocp
    name: "${devicename} Set Output OCP (Max Current)"
    min_value: 0
    max_value: 22
    step: 0.01
    unit_of_measurement: "A"
    icon: "mdi:current-dc"
    address: 84
    value_type: U_WORD
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: set_output_opp
    name: "${devicename} Set Output OPP (Max Power)"
    min_value: 0
    max_value: 1300
    step: 1
    unit_of_measurement: "W"
    icon: "mdi:flash"
    address: 85
    value_type: U_WORD
    multiply: 1

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: set_max_temperature
    name: "${devicename} Set Max Temperature (OTP)"
    min_value: 60
    max_value: 110
    step: 1
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-alert"
    address: 92
    value_type: U_WORD
    multiply: 1

 

  # Защита по энергии (OAH) - 32-bit регистры 88-89
  # Диапазон LCD: 0-99.99 Ah, делитель 100
  - platform: template
    id: set_oah
    name: "${devicename} Set Max Charge (Ah)"
    min_value: 0
    max_value: 99.99
    step: 0.01
    unit_of_measurement: "Ah"
    icon: "mdi:battery-charging-100"
    optimistic: true
    set_action:
      - lambda: |-
          uint32_t value = (uint32_t)(x * 100);  // 60.05 -> 6005
          uint16_t low = value & 0xFFFF;
          uint16_t high = (value >> 16) & 0xFFFF;
          
          ESP_LOGD("set_oah", "Setting %.2f Ah = %u (low=%u, high=%u)", x, value, low, high);
          
          esphome::modbus_controller::ModbusController *controller = id(xy_hub);
          std::vector<uint16_t> data = {low, high};
          esphome::modbus_controller::ModbusCommandItem write_cmd = 
            esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
              controller, 88, 2, data);
          controller->queue_command(write_cmd);

  # Защита по энергии (OWH) - 32-bit регистры 90-91
  # Диапазон LCD: 0-999.9 Wh, делитель 10
  - platform: template
    id: set_owh
    name: "${devicename} Set Max Energy (Wh)"
    min_value: 0
    max_value: 999.9
    step: 0.01
    unit_of_measurement: "Wh"
    icon: "mdi:lightning-bolt"
    optimistic: true
    set_action:
      - lambda: |-
          uint32_t value = (uint32_t)(x * 10);  // 400.4 -> 4004
          uint16_t low = value & 0xFFFF;
          uint16_t high = (value >> 16) & 0xFFFF;
          
          ESP_LOGD("set_owh", "Setting %.1f Wh = %u (low=%u, high=%u)", x, value, low, high);
          
          esphome::modbus_controller::ModbusController *controller = id(xy_hub);
          std::vector<uint16_t> data = {low, high};
          esphome::modbus_controller::ModbusCommandItem write_cmd = 
            esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
              controller, 90, 2, data);
          controller->queue_command(write_cmd);

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: protection_register
    name: "${devicename} Protection Register"
    min_value: 0
    max_value: 255
    step: 1
    address: 16
    value_type: U_WORD
    multiply: 1
    internal: true

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: output_status
    name: "${devicename} Output"
    register_type: holding
    address: 18
    bitmask: 0x1
    device_class: power

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: key_lock
    name: "${devicename} Key Lock"
    register_type: holding
    address: 15
    bitmask: 0x1
    icon: "mdi:lock"

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: constant_current_mode
    name: "${devicename} Constant Current Mode"
    register_type: holding
    address: 17
    bitmask: 0x1
    icon: "mdi:current-dc"

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: over_voltage_protection
    name: "${devicename} Over Voltage Protection"
    register_type: holding
    address: 16
    bitmask: 0x01
    device_class: problem

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: over_current_protection
    name: "${devicename} Over Current Protection"
    register_type: holding
    address: 16
    bitmask: 0x02
    device_class: problem

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: over_power_protection
    name: "${devicename} Over Power Protection"
    register_type: holding
    address: 16
    bitmask: 0x04
    device_class: problem

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: over_temperature_protection
    name: "${devicename} Over Temperature Protection"
    register_type: holding
    address: 16
    bitmask: 0x80
    device_class: problem

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: over_ah_protection
    name: "${devicename} Over Ah Protection (OAH)"
    register_type: holding
    address: 16
    bitmask: 0x10
    device_class: problem



  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: over_wh_protection
    name: "${devicename} Over Wh Protection (OWH)"
    register_type: holding
    address: 16
    bitmask: 0x40
    device_class: problem

  - platform: status
    name: "${devicename} API Status"

switch:
  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: output_switch
    name: "${devicename} Output Switch"
    register_type: holding
    address: 18
    bitmask: 1
    restore_mode: ALWAYS_OFF

  - platform: modbus_controller
    modbus_controller_id: xy_hub
    id: key_lock_switch
    name: "${devicename} Key Lock Switch"
    register_type: holding
    address: 15
    bitmask: 1
    icon: "mdi:lock"

button:
  - platform: restart
    name: ${friendly_name} Node restart

 

select:
  - platform: modbus_controller
    modbus_controller_id: xy_hub
    name: "${devicename} Load Memory Preset"
    address: 29
    value_type: U_WORD
    optionsmap:
      "M0": 0
      "M1": 1
      "M2": 2
      "M3": 3
      "M4": 4
      "M5": 5
      "M6": 6
      "M7": 7
      "M8": 8
      "M9": 9
    icon: "mdi:database"




